// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SubjectHitman.DataAccess;

#nullable disable

namespace SubjectHitman.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SubjectHitman.Domain.Entities.ReportUsage", b =>
                {
                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<bool>("IsFree")
                        .HasColumnType("boolean")
                        .HasColumnName("is_free");

                    b.Property<DateTimeOffset>("OrderedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ordered_at");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.HasKey("ReportId")
                        .HasName("pk_report_usages");

                    b.HasIndex("SubjectId", "OrderedAt")
                        .HasDatabaseName("ix_report_usages_count")
                        .HasFilter("is_free AND status = 1");

                    b.ToTable("report_usages", (string)null);
                });

            modelBuilder.Entity("SubjectHitman.Domain.Entities.SearchKey", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("hash");

                    b.Property<short>("KeyType")
                        .HasColumnType("smallint")
                        .HasColumnName("key_type");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.HasKey("Id")
                        .HasName("pk_search_keys");

                    b.HasIndex("Hash")
                        .HasDatabaseName("ix_search_keys_hash");

                    b.HasIndex("SubjectId", "KeyType", "Hash")
                        .IsUnique()
                        .HasDatabaseName("ix_search_keys_subject_id_key_type_hash");

                    b.ToTable("search_keys", (string)null);
                });

            modelBuilder.Entity("SubjectHitman.Domain.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Inn")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("inn");

                    b.Property<string>("Snils")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("snils");

                    b.HasKey("Id")
                        .HasName("pk_subjects");

                    b.ToTable("subjects", (string)null);
                });

            modelBuilder.Entity("SubjectHitman.Domain.Entities.SubjectDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnName("issue_date");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.Property<string>("Series")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("series");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type_code");

                    b.HasKey("Id")
                        .HasName("pk_subject_documents");

                    b.HasIndex("SubjectId", "TypeCode", "Series", "Number", "IssueDate")
                        .IsUnique()
                        .HasDatabaseName("ix_subject_documents_subject_id_type_code_series_number_issue_");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("SubjectId", "TypeCode", "Series", "Number", "IssueDate"), false);

                    b.ToTable("subject_documents", (string)null);
                });

            modelBuilder.Entity("SubjectHitman.Domain.Entities.SubjectName", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("middle_name");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.HasKey("Id")
                        .HasName("pk_subject_names");

                    b.HasIndex("SubjectId", "LastName", "FirstName", "MiddleName")
                        .IsUnique()
                        .HasDatabaseName("ix_subject_names_subject_id_last_name_first_name_middle_name");

                    b.ToTable("subject_names", (string)null);
                });

            modelBuilder.Entity("SubjectHitman.Domain.Entities.ReportUsage", b =>
                {
                    b.HasOne("SubjectHitman.Domain.Entities.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_report_usages_subjects_subject_id");
                });

            modelBuilder.Entity("SubjectHitman.Domain.Entities.SearchKey", b =>
                {
                    b.HasOne("SubjectHitman.Domain.Entities.Subject", null)
                        .WithMany("SearchKeys")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_search_keys_subjects_subject_id");
                });

            modelBuilder.Entity("SubjectHitman.Domain.Entities.SubjectDocument", b =>
                {
                    b.HasOne("SubjectHitman.Domain.Entities.Subject", null)
                        .WithMany("Documents")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subject_documents_subjects_subject_id");
                });

            modelBuilder.Entity("SubjectHitman.Domain.Entities.SubjectName", b =>
                {
                    b.HasOne("SubjectHitman.Domain.Entities.Subject", null)
                        .WithMany("Names")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subject_names_subjects_subject_id");
                });

            modelBuilder.Entity("SubjectHitman.Domain.Entities.Subject", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Names");

                    b.Navigation("SearchKeys");
                });
#pragma warning restore 612, 618
        }
    }
}
